vich_uploader:
    db_driver: orm
    mappings:
        users_images:
            uri_prefix: '%app.path.users_images%'
            upload_destination: '%kernel.project_dir%/public/%app.path.users_images%'

